// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoSetPrimaryVersion() {
  return window['go']['main']['App']['AutoSetPrimaryVersion']();
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeleteMod(arg1, arg2) {
  return window['go']['main']['App']['DeleteMod'](arg1, arg2);
}

export function DeleteSkin(arg1) {
  return window['go']['main']['App']['DeleteSkin'](arg1);
}

export function DeleteVersion(arg1) {
  return window['go']['main']['App']['DeleteVersion'](arg1);
}

export function DownloadVersion(arg1) {
  return window['go']['main']['App']['DownloadVersion'](arg1);
}

export function DownloadVersionWithCustomName(arg1, arg2) {
  return window['go']['main']['App']['DownloadVersionWithCustomName'](arg1, arg2);
}

export function FetchVersions() {
  return window['go']['main']['App']['FetchVersions']();
}

export function FormatSize(arg1) {
  return window['go']['main']['App']['FormatSize'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGameProcessInfo() {
  return window['go']['main']['App']['GetGameProcessInfo']();
}

export function GetGameStatus() {
  return window['go']['main']['App']['GetGameStatus']();
}

export function GetInstalledVersions() {
  return window['go']['main']['App']['GetInstalledVersions']();
}

export function GetMods(arg1) {
  return window['go']['main']['App']['GetMods'](arg1);
}

export function GetPrimaryVersion() {
  return window['go']['main']['App']['GetPrimaryVersion']();
}

export function GetSkinImage(arg1) {
  return window['go']['main']['App']['GetSkinImage'](arg1);
}

export function GetSkins() {
  return window['go']['main']['App']['GetSkins']();
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function GetVersionsByType(arg1) {
  return window['go']['main']['App']['GetVersionsByType'](arg1);
}

export function ImportMod(arg1, arg2) {
  return window['go']['main']['App']['ImportMod'](arg1, arg2);
}

export function ImportSkin(arg1) {
  return window['go']['main']['App']['ImportSkin'](arg1);
}

export function InstallVersion(arg1) {
  return window['go']['main']['App']['InstallVersion'](arg1);
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function OpenVersionFolder(arg1) {
  return window['go']['main']['App']['OpenVersionFolder'](arg1);
}

export function OpenVersionModsFolder(arg1) {
  return window['go']['main']['App']['OpenVersionModsFolder'](arg1);
}

export function RenameVersion(arg1, arg2) {
  return window['go']['main']['App']['RenameVersion'](arg1, arg2);
}

export function SelectModFile() {
  return window['go']['main']['App']['SelectModFile']();
}

export function SelectSkinFile() {
  return window['go']['main']['App']['SelectSkinFile']();
}

export function SetCurrentVersion(arg1) {
  return window['go']['main']['App']['SetCurrentVersion'](arg1);
}

export function SetManifestURL(arg1) {
  return window['go']['main']['App']['SetManifestURL'](arg1);
}

export function SetMaxConcurrent(arg1) {
  return window['go']['main']['App']['SetMaxConcurrent'](arg1);
}

export function SetPrimaryVersion(arg1) {
  return window['go']['main']['App']['SetPrimaryVersion'](arg1);
}

export function StopGame() {
  return window['go']['main']['App']['StopGame']();
}

export function SyncSkinsToGame(arg1) {
  return window['go']['main']['App']['SyncSkinsToGame'](arg1);
}

export function ToggleMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleMod'](arg1, arg2, arg3);
}

export function VersionExists(arg1) {
  return window['go']['main']['App']['VersionExists'](arg1);
}
