// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {version} from '../models';
import {main} from '../models';
import {mod} from '../models';
import {savegame} from '../models';
import {skin} from '../models';

export function AutoDetectLanguage():Promise<void>;

export function AutoImportVersions():Promise<void>;

export function AutoSetPrimaryVersion():Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CancelModpackInstall():Promise<void>;

export function CheckDotNetRuntime(arg1:string):Promise<Record<string, any>>;

export function CheckUpdate():Promise<Record<string, any>>;

export function CheckUpdateWithForce(arg1:boolean):Promise<Record<string, any>>;

export function ClearBackground():Promise<void>;

export function DeleteFurniture(arg1:string,arg2:string):Promise<void>;

export function DeleteMod(arg1:string,arg2:string):Promise<void>;

export function DeleteSaveGame(arg1:string,arg2:string):Promise<void>;

export function DeleteSkin(arg1:string):Promise<void>;

export function DeleteTexture(arg1:string,arg2:string):Promise<void>;

export function DeleteVersion(arg1:string):Promise<void>;

export function DetectGameVersion(arg1:string):Promise<string>;

export function DownloadFurnitureFromURL(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadModFromURL(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadSaveGameFromURL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadSkinFromURL(arg1:string,arg2:string):Promise<void>;

export function DownloadTextureFromURL(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadVersion(arg1:string):Promise<void>;

export function DownloadVersionWithCustomName(arg1:string,arg2:string):Promise<void>;

export function ExportSaveGame(arg1:string,arg2:string):Promise<boolean>;

export function ExportSaveGameAsModpack(arg1:string,arg2:string):Promise<boolean>;

export function FetchVersions():Promise<Array<version.Version>>;

export function FormatSize(arg1:number):Promise<string>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetBackgroundImage():Promise<string>;

export function GetBackgroundImageBase64():Promise<string>;

export function GetConfig():Promise<Record<string, any>>;

export function GetFurnitures(arg1:string):Promise<Array<main.Furniture>>;

export function GetGameProcessInfo():Promise<any>;

export function GetGameStatus():Promise<string>;

export function GetInstalledVersions():Promise<Array<version.Version>>;

export function GetModSources():Promise<Array<Record<string, any>>>;

export function GetMods(arg1:string):Promise<Array<mod.Mod>>;

export function GetPrimaryVersion():Promise<Record<string, any>>;

export function GetSaveGames(arg1:string):Promise<Array<savegame.SaveGame>>;

export function GetSaveRequiredMods(arg1:string,arg2:string):Promise<Array<savegame.SaveRequiredMod>>;

export function GetSkinImage(arg1:string):Promise<string>;

export function GetSkins():Promise<Array<skin.Skin>>;

export function GetSystemLanguage():Promise<string>;

export function GetTextures(arg1:string):Promise<Array<main.Texture>>;

export function GetVersions():Promise<Array<version.Version>>;

export function GetVersionsByType(arg1:string):Promise<Array<version.Version>>;

export function HasBackground():Promise<boolean>;

export function HttpRequest(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string):Promise<string>;

export function ImportFurniture(arg1:string,arg2:string):Promise<void>;

export function ImportGameVersion(arg1:string):Promise<string>;

export function ImportMod(arg1:string,arg2:string):Promise<void>;

export function ImportSaveGame(arg1:string,arg2:string):Promise<void>;

export function ImportSkin(arg1:string):Promise<void>;

export function ImportTexture(arg1:string,arg2:string):Promise<void>;

export function InspectArchive(arg1:string):Promise<string>;

export function InstallDotNetRuntime(arg1:string):Promise<void>;

export function InstallFromArchive(arg1:string,arg2:string):Promise<string>;

export function InstallModpack(arg1:string):Promise<string>;

export function InstallModpackWithProgress(arg1:string,arg2:string):Promise<string>;

export function InstallVersion(arg1:string):Promise<void>;

export function IsOnlineVersion(arg1:string):Promise<boolean>;

export function LaunchGame(arg1:string):Promise<void>;

export function OpenFurnitureFolder(arg1:string):Promise<void>;

export function OpenSaveGameFolder(arg1:string,arg2:string):Promise<void>;

export function OpenTextureFolder(arg1:string):Promise<void>;

export function OpenVersionFolder(arg1:string):Promise<void>;

export function OpenVersionModsFolder(arg1:string):Promise<void>;

export function ParseModpack(arg1:string):Promise<Record<string, any>>;

export function PreviewSaveGame(arg1:string):Promise<savegame.SaveGame>;

export function PreviewSaveRequiredMods(arg1:string):Promise<Array<savegame.SaveRequiredMod>>;

export function RenameFurniture(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameSaveGame(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameTexture(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameVersion(arg1:string,arg2:string):Promise<void>;

export function SaveManifestSources(arg1:Array<Record<string, any>>):Promise<void>;

export function SaveModSources(arg1:Array<Record<string, any>>):Promise<void>;

export function SelectArchiveFile():Promise<string>;

export function SelectBackgroundFile():Promise<string>;

export function SelectFurnitureFile():Promise<string>;

export function SelectGameFolder():Promise<string>;

export function SelectModFile():Promise<string>;

export function SelectModpackFile():Promise<string>;

export function SelectSaveGameFile():Promise<string>;

export function SelectSkinFile():Promise<string>;

export function SelectTextureFile():Promise<string>;

export function SetAutoCheckRuntime(arg1:boolean):Promise<void>;

export function SetBackground(arg1:string):Promise<string>;

export function SetCurrentManifestSource(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetManifestURL(arg1:string):Promise<void>;

export function SetMaxConcurrent(arg1:number):Promise<void>;

export function SetPrimaryVersion(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetUpdateRemindDisabled(arg1:boolean):Promise<void>;

export function StopGame():Promise<void>;

export function SyncSkinsToGame(arg1:string):Promise<void>;

export function ToggleMod(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function VersionExists(arg1:string):Promise<boolean>;
