// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {version} from '../models';
import {mod} from '../models';
import {skin} from '../models';

export function AutoSetPrimaryVersion():Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckUpdate():Promise<Record<string, any>>;

export function DeleteMod(arg1:string,arg2:string):Promise<void>;

export function DeleteSkin(arg1:string):Promise<void>;

export function DeleteVersion(arg1:string):Promise<void>;

export function DownloadVersion(arg1:string):Promise<void>;

export function DownloadVersionWithCustomName(arg1:string,arg2:string):Promise<void>;

export function FetchVersions():Promise<Array<version.Version>>;

export function FormatSize(arg1:number):Promise<string>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetGameProcessInfo():Promise<any>;

export function GetGameStatus():Promise<string>;

export function GetInstalledVersions():Promise<Array<version.Version>>;

export function GetMods(arg1:string):Promise<Array<mod.Mod>>;

export function GetPrimaryVersion():Promise<Record<string, any>>;

export function GetSkinImage(arg1:string):Promise<string>;

export function GetSkins():Promise<Array<skin.Skin>>;

export function GetVersions():Promise<Array<version.Version>>;

export function GetVersionsByType(arg1:string):Promise<Array<version.Version>>;

export function ImportMod(arg1:string,arg2:string):Promise<void>;

export function ImportSkin(arg1:string):Promise<void>;

export function InstallVersion(arg1:string):Promise<void>;

export function LaunchGame(arg1:string):Promise<void>;

export function OpenVersionFolder(arg1:string):Promise<void>;

export function OpenVersionModsFolder(arg1:string):Promise<void>;

export function RenameVersion(arg1:string,arg2:string):Promise<void>;

export function SelectModFile():Promise<string>;

export function SelectSkinFile():Promise<string>;

export function SetCurrentVersion(arg1:string):Promise<void>;

export function SetManifestURL(arg1:string):Promise<void>;

export function SetMaxConcurrent(arg1:number):Promise<void>;

export function SetPrimaryVersion(arg1:string):Promise<void>;

export function StopGame():Promise<void>;

export function SyncSkinsToGame(arg1:string):Promise<void>;

export function ToggleMod(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function VersionExists(arg1:string):Promise<boolean>;
