// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDetectLanguage() {
  return window['go']['main']['App']['AutoDetectLanguage']();
}

export function AutoImportVersions() {
  return window['go']['main']['App']['AutoImportVersions']();
}

export function AutoSetPrimaryVersion() {
  return window['go']['main']['App']['AutoSetPrimaryVersion']();
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CancelModpackInstall() {
  return window['go']['main']['App']['CancelModpackInstall']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CheckUpdateWithForce(arg1) {
  return window['go']['main']['App']['CheckUpdateWithForce'](arg1);
}

export function ClearBackground() {
  return window['go']['main']['App']['ClearBackground']();
}

export function DeleteFurniture(arg1, arg2) {
  return window['go']['main']['App']['DeleteFurniture'](arg1, arg2);
}

export function DeleteMod(arg1, arg2) {
  return window['go']['main']['App']['DeleteMod'](arg1, arg2);
}

export function DeleteSaveGame(arg1, arg2) {
  return window['go']['main']['App']['DeleteSaveGame'](arg1, arg2);
}

export function DeleteSkin(arg1) {
  return window['go']['main']['App']['DeleteSkin'](arg1);
}

export function DeleteTexture(arg1, arg2) {
  return window['go']['main']['App']['DeleteTexture'](arg1, arg2);
}

export function DeleteVersion(arg1) {
  return window['go']['main']['App']['DeleteVersion'](arg1);
}

export function DownloadFurnitureFromURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFurnitureFromURL'](arg1, arg2, arg3);
}

export function DownloadModFromURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadModFromURL'](arg1, arg2, arg3);
}

export function DownloadSaveGameFromURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadSaveGameFromURL'](arg1, arg2, arg3);
}

export function DownloadSkinFromURL(arg1, arg2) {
  return window['go']['main']['App']['DownloadSkinFromURL'](arg1, arg2);
}

export function DownloadTextureFromURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadTextureFromURL'](arg1, arg2, arg3);
}

export function DownloadVersion(arg1) {
  return window['go']['main']['App']['DownloadVersion'](arg1);
}

export function DownloadVersionWithCustomName(arg1, arg2) {
  return window['go']['main']['App']['DownloadVersionWithCustomName'](arg1, arg2);
}

export function ExportSaveGame(arg1, arg2) {
  return window['go']['main']['App']['ExportSaveGame'](arg1, arg2);
}

export function ExportSaveGameAsModpack(arg1, arg2) {
  return window['go']['main']['App']['ExportSaveGameAsModpack'](arg1, arg2);
}

export function FetchVersions() {
  return window['go']['main']['App']['FetchVersions']();
}

export function FormatSize(arg1) {
  return window['go']['main']['App']['FormatSize'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBackgroundImage() {
  return window['go']['main']['App']['GetBackgroundImage']();
}

export function GetBackgroundImageBase64() {
  return window['go']['main']['App']['GetBackgroundImageBase64']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFurnitures(arg1) {
  return window['go']['main']['App']['GetFurnitures'](arg1);
}

export function GetGameProcessInfo() {
  return window['go']['main']['App']['GetGameProcessInfo']();
}

export function GetGameStatus() {
  return window['go']['main']['App']['GetGameStatus']();
}

export function GetInstalledVersions() {
  return window['go']['main']['App']['GetInstalledVersions']();
}

export function GetModSources() {
  return window['go']['main']['App']['GetModSources']();
}

export function GetMods(arg1) {
  return window['go']['main']['App']['GetMods'](arg1);
}

export function GetPrimaryVersion() {
  return window['go']['main']['App']['GetPrimaryVersion']();
}

export function GetSaveGames(arg1) {
  return window['go']['main']['App']['GetSaveGames'](arg1);
}

export function GetSkinImage(arg1) {
  return window['go']['main']['App']['GetSkinImage'](arg1);
}

export function GetSkins() {
  return window['go']['main']['App']['GetSkins']();
}

export function GetSystemLanguage() {
  return window['go']['main']['App']['GetSystemLanguage']();
}

export function GetTextures(arg1) {
  return window['go']['main']['App']['GetTextures'](arg1);
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function GetVersionsByType(arg1) {
  return window['go']['main']['App']['GetVersionsByType'](arg1);
}

export function HasBackground() {
  return window['go']['main']['App']['HasBackground']();
}

export function ImportFurniture(arg1, arg2) {
  return window['go']['main']['App']['ImportFurniture'](arg1, arg2);
}

export function ImportGameVersion(arg1) {
  return window['go']['main']['App']['ImportGameVersion'](arg1);
}

export function ImportMod(arg1, arg2) {
  return window['go']['main']['App']['ImportMod'](arg1, arg2);
}

export function ImportSaveGame(arg1, arg2) {
  return window['go']['main']['App']['ImportSaveGame'](arg1, arg2);
}

export function ImportSkin(arg1) {
  return window['go']['main']['App']['ImportSkin'](arg1);
}

export function ImportTexture(arg1, arg2) {
  return window['go']['main']['App']['ImportTexture'](arg1, arg2);
}

export function InstallFromArchive(arg1, arg2) {
  return window['go']['main']['App']['InstallFromArchive'](arg1, arg2);
}

export function InstallModpack(arg1) {
  return window['go']['main']['App']['InstallModpack'](arg1);
}

export function InstallModpackWithProgress(arg1, arg2) {
  return window['go']['main']['App']['InstallModpackWithProgress'](arg1, arg2);
}

export function InstallVersion(arg1) {
  return window['go']['main']['App']['InstallVersion'](arg1);
}

export function IsOnlineVersion(arg1) {
  return window['go']['main']['App']['IsOnlineVersion'](arg1);
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function OpenFurnitureFolder(arg1) {
  return window['go']['main']['App']['OpenFurnitureFolder'](arg1);
}

export function OpenSaveGameFolder(arg1, arg2) {
  return window['go']['main']['App']['OpenSaveGameFolder'](arg1, arg2);
}

export function OpenTextureFolder(arg1) {
  return window['go']['main']['App']['OpenTextureFolder'](arg1);
}

export function OpenVersionFolder(arg1) {
  return window['go']['main']['App']['OpenVersionFolder'](arg1);
}

export function OpenVersionModsFolder(arg1) {
  return window['go']['main']['App']['OpenVersionModsFolder'](arg1);
}

export function ParseModpack(arg1) {
  return window['go']['main']['App']['ParseModpack'](arg1);
}

export function PreviewSaveGame(arg1) {
  return window['go']['main']['App']['PreviewSaveGame'](arg1);
}

export function RenameFurniture(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFurniture'](arg1, arg2, arg3);
}

export function RenameSaveGame(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameSaveGame'](arg1, arg2, arg3);
}

export function RenameTexture(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameTexture'](arg1, arg2, arg3);
}

export function RenameVersion(arg1, arg2) {
  return window['go']['main']['App']['RenameVersion'](arg1, arg2);
}

export function SaveManifestSources(arg1) {
  return window['go']['main']['App']['SaveManifestSources'](arg1);
}

export function SaveModSources(arg1) {
  return window['go']['main']['App']['SaveModSources'](arg1);
}

export function SelectArchiveFile() {
  return window['go']['main']['App']['SelectArchiveFile']();
}

export function SelectBackgroundFile() {
  return window['go']['main']['App']['SelectBackgroundFile']();
}

export function SelectFurnitureFile() {
  return window['go']['main']['App']['SelectFurnitureFile']();
}

export function SelectGameFolder() {
  return window['go']['main']['App']['SelectGameFolder']();
}

export function SelectModFile() {
  return window['go']['main']['App']['SelectModFile']();
}

export function SelectModpackFile() {
  return window['go']['main']['App']['SelectModpackFile']();
}

export function SelectSaveGameFile() {
  return window['go']['main']['App']['SelectSaveGameFile']();
}

export function SelectSkinFile() {
  return window['go']['main']['App']['SelectSkinFile']();
}

export function SelectTextureFile() {
  return window['go']['main']['App']['SelectTextureFile']();
}

export function SetBackground(arg1) {
  return window['go']['main']['App']['SetBackground'](arg1);
}

export function SetCurrentManifestSource(arg1) {
  return window['go']['main']['App']['SetCurrentManifestSource'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetManifestURL(arg1) {
  return window['go']['main']['App']['SetManifestURL'](arg1);
}

export function SetMaxConcurrent(arg1) {
  return window['go']['main']['App']['SetMaxConcurrent'](arg1);
}

export function SetPrimaryVersion(arg1) {
  return window['go']['main']['App']['SetPrimaryVersion'](arg1);
}

export function SetUpdateRemindDisabled(arg1) {
  return window['go']['main']['App']['SetUpdateRemindDisabled'](arg1);
}

export function StopGame() {
  return window['go']['main']['App']['StopGame']();
}

export function SyncSkinsToGame(arg1) {
  return window['go']['main']['App']['SyncSkinsToGame'](arg1);
}

export function ToggleMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleMod'](arg1, arg2, arg3);
}

export function VersionExists(arg1) {
  return window['go']['main']['App']['VersionExists'](arg1);
}
